import React, { useState } from 'react';

function ExportButton({ trade, myRoster, opponent }) {
  const [copied, setCopied] = useState(false);

  const formatTradeForSleeper = () => {
    if (!trade || !myRoster || !opponent) return '';

    const parts = [];

    // Header
    parts.push(`🔄 TRADE PROPOSAL`);
    parts.push('');

    // You give section
    parts.push(`📤 ${myRoster.teamName || 'You'} sends:`);
    if (trade.myAssets.players.length > 0) {
      trade.myAssets.players.forEach(player => {
        parts.push(`  • ${player.name} (${player.position}) - ${player.value || 0}`);
      });
    }
    if (trade.myAssets.picks.length > 0) {
      trade.myAssets.picks.forEach(pick => {
        parts.push(`  • ${pick.season} Round ${pick.round} - ${pick.value || 0}`);
      });
    }
    parts.push('');

    // You receive section
    parts.push(`📥 ${myRoster.teamName || 'You'} receives:`);
    if (trade.opponentAssets.players.length > 0) {
      trade.opponentAssets.players.forEach(player => {
        parts.push(`  • ${player.name} (${player.position}) - ${player.value || 0}`);
      });
    }
    if (trade.opponentAssets.picks.length > 0) {
      trade.opponentAssets.picks.forEach(pick => {
        parts.push(`  • ${pick.season} Round ${pick.round} - ${pick.value || 0}`);
      });
    }
    parts.push('');

    // Value breakdown
    const myTotal = (trade.myAssets.totalValue || 0);
    const opponentTotal = (trade.opponentAssets.totalValue || 0);
    const difference = opponentTotal - myTotal;

    parts.push(`💰 Value Breakdown:`);
    parts.push(`  You give: ${myTotal}`);
    parts.push(`  You get: ${opponentTotal}`);
    parts.push(`  Net gain: ${difference > 0 ? '+' : ''}${difference}`);
    parts.push('');

    // Verdict
    if (difference > 500) {
      parts.push(`✅ GREAT DEAL - You win by ${difference}!`);
    } else if (difference > 0) {
      parts.push(`👍 GOOD DEAL - You win by ${difference}`);
    } else if (difference === 0) {
      parts.push(`⚖️ FAIR TRADE - Even value`);
    } else {
      parts.push(`⚠️ BAD DEAL - You lose by ${Math.abs(difference)}`);
    }

    parts.push('');
    parts.push('Generated by Fantasy Fleece Finder');

    return parts.join('\n');
  };

  const handleCopy = async () => {
    const formatted = formatTradeForSleeper();

    try {
      await navigator.clipboard.writeText(formatted);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
      // Fallback for older browsers
      const textarea = document.createElement('textarea');
      textarea.value = formatted;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      try {
        document.execCommand('copy');
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (fallbackErr) {
        console.error('Fallback copy failed:', fallbackErr);
      }
      document.body.removeChild(textarea);
    }
  };

  const isDisabled = !trade ||
                      (trade.myAssets.players.length === 0 && trade.myAssets.picks.length === 0) ||
                      (trade.opponentAssets.players.length === 0 && trade.opponentAssets.picks.length === 0);

  return (
    <>
      <button
        className="btn btn-secondary"
        onClick={handleCopy}
        disabled={isDisabled}
        title="Copy trade to clipboard for Sleeper chat"
      >
        {copied ? '✓ Copied!' : '📋 Copy to Clipboard'}
      </button>

      {copied && (
        <div className="toast-notification">
          Trade copied to clipboard!
        </div>
      )}
    </>
  );
}

export default ExportButton;
